language: python
dist: xenial   # required for Python >= 3.7
python:
- '3.6'
- '3.7'
#- '3.8-dev'
# command to install dependencies
install:
  - pip install -e .[dev]  --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-openeo/simple
# command to run tests
script:
  - pytest