language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-openeo/simple
  - pip install -e .
# command to run tests
script:
  - pytest